/*Games Table*/
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].Games(
	[GameID] [int] IDENTITY (4000, 1) NOT NULL,
	[GameName] [varchar](35) NOT NULL,
	[Description] [varchar](500) NOT NULL,
	[Spectators] [int] NOT NULL,
	[Player1] [varchar](35) NOT NULL,
	[Player2] [varchar](35) NOT NULL,
	[WinningPlayer] [varchar](35) NOT NULL,
	[Created] [DATE] NOT NULL,
 CONSTRAINT [PK_Games] PRIMARY KEY CLUSTERED 
(
	[GameID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

/*teams table*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Players](
	[PlayerID] [int] IDENTITY (4000, 1) NOT NULL,
	[PlayerName] [varchar](35) NOT NULL,
	[Wins] [int] NOT NULL,
	[Losses] [int] NOT NULL,
 CONSTRAINT [PK_Players] PRIMARY KEY CLUSTERED 
(
	[PlayerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO